/**
 * Tests for auditoria/actions.ts (PR #415 — Tech Lead WARNs fix).
 *
 * Covers:
 * 1. userName shows "Sistema" when the audit log has userId: null (system
 *    events generated by SLA workers have no authenticated user).
 * 2. listAuditLogs maps log.user?.name correctly: named user → user name,
 *    null user → "Sistema".
 */

import { describe, it, expect, vi, beforeEach } from "vitest";

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

const mockRequireAdmin = vi.fn().mockResolvedValue(undefined);

vi.mock("@/lib/session", () => ({
  requireAdmin: () => mockRequireAdmin(),
  getSession: vi.fn().mockResolvedValue({ userId: "user-1", role: "ADMIN" }),
}));

const mockAuditLogFindMany = vi.fn();
const mockAuditLogCount = vi.fn().mockResolvedValue(0);

vi.mock("@/lib/trace-context", () => ({
  traceStore: { getStore: vi.fn().mockReturnValue(undefined) },
}));

vi.mock("@/lib/prisma", () => ({
  prisma: {
    auditLog: {
      findMany: (...args: unknown[]) => mockAuditLogFindMany(...args),
      count: (...args: unknown[]) => mockAuditLogCount(...args),
    },
    user: { findMany: vi.fn().mockResolvedValue([]) },
    company: { findMany: vi.fn().mockResolvedValue([]) },
  },
}));

vi.mock("@/lib/logger", () => {
  const _log = { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn(), child: vi.fn() };
  return {
    logger: _log,
    createChildLogger: vi.fn(() => _log),
    sanitizeParams: vi.fn((obj: Record<string, unknown>) => obj),
    truncateForLog: vi.fn((v: unknown) => v),
    classifyError: vi.fn(() => "INTERNAL_ERROR"),
    classifyErrorByStatus: vi.fn(() => "INTERNAL_ERROR"),
    ErrorCode: {
      AUTH_FAILED: "AUTH_FAILED",
      VALIDATION_ERROR: "VALIDATION_ERROR",
      NOT_FOUND: "NOT_FOUND",
      PERMISSION_DENIED: "PERMISSION_DENIED",
      EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
      DATABASE_ERROR: "DATABASE_ERROR",
      ENCRYPTION_ERROR: "ENCRYPTION_ERROR",
      RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
      INTERNAL_ERROR: "INTERNAL_ERROR",
      AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    },
    MAX_LOG_ARG_SIZE: 10240,
  };
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeAuditLog(overrides: Record<string, unknown> = {}) {
  return {
    id: "log-1",
    userId: null,
    action: "SLA_BREACHED",
    entity: "Ticket",
    entityId: "tk-1",
    companyId: "co-1",
    ipAddress: null,
    createdAt: new Date("2026-03-30T10:00:00Z"),
    user: null,
    company: { id: "co-1", nomeFantasia: "Empresa Teste" },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Import after mocks
// ---------------------------------------------------------------------------

import { listAuditLogs } from "../actions";

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

beforeEach(() => {
  vi.clearAllMocks();
  mockRequireAdmin.mockResolvedValue(undefined);
  mockAuditLogCount.mockResolvedValue(1);
});

describe("listAuditLogs — userName display", () => {
  it('shows "Sistema" when userId is null (system-generated audit log)', async () => {
    mockAuditLogFindMany.mockResolvedValue([makeAuditLog()]);

    const result = await listAuditLogs({});

    expect(result.data).toHaveLength(1);
    expect(result.data[0].userName).toBe("Sistema");
    expect(result.data[0].userId).toBeNull();
  });

  it("shows actual user name when userId is set", async () => {
    mockAuditLogFindMany.mockResolvedValue([
      makeAuditLog({
        userId: "user-42",
        user: { id: "user-42", name: "João Silva" },
      }),
    ]);

    const result = await listAuditLogs({});

    expect(result.data[0].userName).toBe("João Silva");
    expect(result.data[0].userId).toBe("user-42");
  });

  it('falls back to "Sistema" when user relation is present but name is nullish', async () => {
    mockAuditLogFindMany.mockResolvedValue([
      makeAuditLog({
        userId: "user-x",
        user: { id: "user-x", name: null },
      }),
    ]);

    const result = await listAuditLogs({});

    // null name also falls back to "Sistema"
    expect(result.data[0].userName).toBe("Sistema");
  });

  it("returns correct pagination metadata", async () => {
    mockAuditLogFindMany.mockResolvedValue([makeAuditLog()]);
    mockAuditLogCount.mockResolvedValue(5);

    const result = await listAuditLogs({ page: 1, pageSize: 2 });

    expect(result.total).toBe(5);
    expect(result.totalPages).toBe(3);
    expect(result.page).toBe(1);
    expect(result.pageSize).toBe(2);
  });
});
