// ─── Email Sanitization Utilities ────────────────────────────────────────────
// Pure utility functions — NOT server actions.
// Kept separate from tool-executor.ts so that "use server" only wraps async exports.
// See: https://github.com/diogenesmendes01/MendesAplication/issues/109

// NOTE: <a> tags are intentionally excluded from outbound email sanitization.
// Allowing clickable links generated by the AI in emails would create phishing
// and tracking risks (the AI could craft misleading hrefs). If links become
// necessary in the future, add <a> with href-only attribute filtering and
// replace this regex-based approach with the `sanitize-html` package (TODO #103).
//
// ⚠️ KNOWN LIMITATION — Regex edge case: the pattern `[^>]*` used to strip
// attributes stops at the first `>` character, even when `>` appears inside
// an attribute value (e.g. `<p class="a>b">`). This can cause incomplete
// sanitization when receiving malformed HTML via email. Acceptable tradeoff
// for current volume; switch to `sanitize-html` (TODO #103) before high-volume
// production rollout.
const ALLOWED_EMAIL_TAGS = new Set(["b", "i", "br", "p", "ul", "li", "strong", "em"]);

// Solução segura: strip TUDO e reinsere somente as tags permitidas via whitelist,
// sem depender de regex para preservar qualquer tag com atributos.
export function sanitizeEmailHtml(input: string): string {
  // Tira todos os atributos de todas as tags primeiro; grupos separados para open/close
  // evitam ambiguidade de captura que permitia bypass via atributos malformados.
  const noAttrs = input.replace(
    /<([a-zA-Z]+)[^>]*\/?>|<\/([a-zA-Z]+)>/gi,
    (match, openTag, closeTag) => {
      const tag = (openTag || closeTag).toLowerCase();
      if (!ALLOWED_EMAIL_TAGS.has(tag)) return "";
      return closeTag
        ? `</${tag}>`
        : match.trimEnd().endsWith("/>")
          ? `<${tag} />`
          : `<${tag}>`;
    }
  );
  return noAttrs;
}
